### ISSUE TITLE
Change ASCII pic to this

### ISSUE THREAD

**Issue by MichalPaszkiewicz** [MichalPaszkiewicz/Manatee#9]
//....................xXXXXx.................//
//...............xXXXX......XXXXXXx..........//
//...XXx.....xXXX..................XXXXXXx...//
//.X....XXXXX.............................Xx.//
//X....................................O....X//
//.X....xXXXXXXx.............X.....X...------//
//...XXX........XXx.......xXX.X.....X....xXX.//
//.................XXXXXXX....X.....XXXX.....//
//.......MANATEE...............X...xX........//
//..............................XXXX.........//

OR DIE

**Comment by beckyzorz** [comment]
Lol.

**Comment by MichalPaszkiewicz** [comment]
Fixed
